- hosts: localhost
  become: true
  tasks:
  - name: download
    shell: curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - name: executable
    shell: chmod +x /usr/local/bin/docker-compose

